In [5]:
# сложение векторов
import numpy as np
vec1 = np.array([2,4,7,2.5]) # если сложить list,
                            #то получится просто 1 объедененный список
vec2 = np.array([12,6,3.6,13])
print(vec1 + vec2)
# без numpy можно сложить так:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
print(list1 + list2) # не так
[x + y for x, y in zip(list1, list2)] # так 
print(vec1*vec2)

[14.  10.  10.6 15.5]
[2, 4, 7, 2.5, 12, 6, 3.6, 13]
[24.  24.  25.2 32.5]


#### Для совершения арифметических операций с векторами они должны быть одинаковой длины.

In [6]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])
print(vec1*vec2) # ошибка, т.к. длина разная


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [8]:
# вектор можно умножить на 1 число
vec = np.arange(5)
print(vec)
print(vec* 10)
print(vec ** 2)

[0 1 2 3 4]
[ 0 10 20 30 40]
[ 0  1  4  9 16]


In [11]:
vec1 = np.array([2,4,7,2.5])
vec2 = np.array([12,6,3.6,13])
print(vec1 < vec2)
print(vec1 < 5)

[ True  True False  True]
[ True  True False  True]


#### Продвинутые операции с вектором

In [19]:
vec = np.array([3,4])
# расчет длины математически
length = np.sqrt(np.sum(vec ** 2))
print(length)
# расчет длины вектора с помощью подмодуля Linalg!!!!
length = np.linalg.norm(vec)
print(length)

# расстоние между векторами
vec1 = np.array([0,3,5])
vec2 = np.array([12,4,7])
distance = np.sqrt(np.sum((vec1 - vec2)**2))
print(distance)
# расстояние между векторами с помощью Linalg!!
distance = np.linalg.norm(vec1 - vec2)
print(distance)

# скалярное произведение:
vec1 = np.arange(1,6)
vec2 = np.linspace(10,20,5)
scolar_product = np.sum(vec1*vec2)
print(scolar_product)
# скалярное произведение в помощью функций numpy
scolar_product = np.dot(vec1, vec2)
print(scolar_product)

5.0
5.0
12.206555615733702
12.206555615733702
250.0
250.0


In [22]:
# поиск max и min в функциях
vec = np.array([2,7,18,28,18,1,8,4])
print(vec.min()) # 1й способ записи
print(vec.max())
print(np.max(vec)) # 2й способ записи
print(np.min(vec))

# среднее значение
print(vec.mean())

1
28
28
1


Напишите функцию min_max_dist(*vectors), которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

In [1]:
import numpy as np

def min_max_dist(*vectors):
    dists = list()
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            dists.append(np.linalg.norm(vectors[i] - vectors[j]))
    return (min(dists), max(dists))

In [2]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)

Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

In [ ]:
import numpy as np

def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False