In [1]:
import numpy as np
np.random.rand() # случайное число от 0 (включительно) до 1 (не вклюительно)

0.7723452672075993

In [9]:
print(np.random.rand()*100) # чтобы получить случайное число до 100
print(np.random.rand(5)) # массив из 5 случ чисел
print(np.random.rand(2, 3)) # массив 2 на 3 из случайных чисел


79.28513559084578
[0.67705722 0.95159376 0.5386027  0.98932709 0.41385523]
[[0.74659053 0.19278883 0.59035963]
 [0.76673631 0.58903125 0.37455945]]


In [10]:
np.random.rand(2, 2, 4, 10, 12, 23)

array([[[[[[9.78885558e-01, 7.08408159e-01, 2.42234895e-01, ...,
            8.21480106e-01, 3.33255507e-01, 9.83126027e-01],
           [1.01812591e-01, 5.52639239e-02, 4.53699868e-01, ...,
            4.98124289e-01, 4.43777088e-01, 3.00336209e-01],
           [1.51012327e-01, 1.03229360e-02, 2.21534697e-01, ...,
            9.72418980e-01, 8.40554790e-01, 7.92871138e-01],
           ...,
           [4.31820406e-01, 5.84821769e-01, 1.01909729e-01, ...,
            4.43995234e-01, 8.99656728e-01, 1.08369297e-01],
           [9.09772773e-01, 6.17608297e-02, 8.58928778e-01, ...,
            7.14591436e-01, 9.43837295e-01, 1.93785093e-01],
           [8.92313061e-01, 8.96441648e-01, 5.25802614e-01, ...,
            3.50854326e-01, 6.36470759e-01, 7.97007578e-01]],

          [[9.22836173e-01, 9.85790109e-02, 5.51654727e-01, ...,
            8.03823034e-01, 4.40047594e-01, 5.20976136e-01],
           [5.31915276e-02, 4.06319187e-01, 6.47580441e-02, ...,
            2.45715689e-01, 6.86226

In [13]:
# чтобы передать картеж необходимо распоковать его
shape = (3,4)
print(np.random.rand(*shape)) # без распаковки будет ОШИБКА
# чтобы без ошибок забирать картежи есть другой способ:
print(np.random.sample(shape)) # sample не сильно отличаетс от rand и ее удобнее
                            # использовать, когда нужно хранить размернось
                            # массива в картеже

[[0.65486374 0.20518751 0.06369714 0.13845292]
 [0.57740122 0.55699733 0.38817871 0.68333097]
 [0.31909234 0.25511874 0.25717814 0.28351861]]
[[0.01573971 0.99651166 0.76275435 0.86746562]
 [0.01504179 0.06768263 0.10127802 0.78186273]
 [0.55853397 0.54243974 0.68585835 0.29502639]]


#### Задаем размерность диапазона

In [18]:
# функция uniform(low=0.0, high=1.0, size=None)
# size задается или 1 число или кортежем - это размерность
print(np.random.uniform())
print(np.random.uniform(-30, 50))
print(np.random.uniform(0.5, 0.75, size=5))
print(np.random.uniform(-1000, 500, size=(2, 3)))

0.07565910796325004
17.38928402785728
[0.66078931 0.57811924 0.50405666 0.51468066 0.67723509]
[[ -15.10821801 -749.5590359  -511.86428761]
 [-324.57409378 -789.1197665  -512.04905544]]


In [20]:
# Генерация int с помощью функции
# randint(low, high=None, size=None, dtype=int) - обязателньо
# указывать хотя бы 1 параметр, верхняя граница не включается
print(np.random.randint(4, size=(2, 3)))
print(np.random.randint(6, 12, size=(3, 3)))


[[0 2 0]
 [0 1 2]]
[[10  7 11]
 [11  8 11]
 [ 9  8 11]]


In [58]:
# перемешивание данных в массиве
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr)) # выводит NONE 
print(arr)
# чтобы не перезаписывать текущий массив можно использовать random.permutation
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shelffled = np.random.permutation(playlist)
print(shelffled) # массив
print(playlist) # список 

# чтобы получить случайный набор объектов из массива используется функция
# randome.choice(a, size=None, replace=True)
# a - число для генерации масиива arange(a) 
# size - форма массива, число или кортеж
# replace - могут ли элементы повторяться (по умолчанию могут).
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=2, replace=False) # будет ошибка если
                                        # задаnm размер больше списка на входе
print(choice)
choice = np.random.choice([1,2,3,4,5,6], size=10) # тут нет ошибка, т.к. replace по
                                        # умолчаниб True и значения могут повторятся
print(choice)

[0 1 2 3 4 5]
None
[2 5 3 1 0 4]
['Pink Floyd' 'The Beatles' 'Deep Purple' 'ACDC']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']
['Nikita' 'John']
[6 2 4 6 3 1 2 1 5 1]


#### Получение одинаковых воспроизводимых случайных чисел

In [93]:
# Самостоятельно задать seed в NumPy можно с помощью функции
# np.random.seed(<np.uint32>). Число в скобках должно быть в пределах от
# 0 до 2**32 - 1 (=4294967295).
print(np.random.seed(23)) # если меняет число в скопаках,
                            #то меняеютс и значение в массиве
print(np.random.randint(10, size=(3,4)))
print(np.random.randint(10, size=(3,4)))


None
[[3 6 8 9]
 [6 8 7 9]
 [3 6 1 2]]
[[5 5 0 5]
 [0 9 9 3]
 [1 7 4 1]]


In [87]:
np.random.seed(100)
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]


In [96]:
np.random.seed(2021)
simple = np.random.rand()
randoms = np.random.uniform(-150, 2021, size=120)
table = np.random.randint(1, 101, size=(3, 2))
even = np.arange(2, 17, 2)
select = np.random.choice(even, replace=False)
triplet = np.random.permutation(select)

In [103]:
np.random.seed(2021)
# В simple сохраните случайное число в диапазоне от 0 до 1
simple = np.random.rand()
# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их
# в переменную randoms
randoms = np.random.uniform(-150, 2021, size=120)
# Получите массив из случайных целых чисел от 1 до 100 (включительно)
# из 3 строк и 2 столбцов. Сохраните результат в table
table = np.random.randint(1, 101, size=(3,2))
# В переменную even сохраните чётные числа от 2 до 16 (включительно)
even = np.arange(2,17,2)
# Скопируйте even в переменную mix. Перемешайте числа в mix так,
# чтобы массив mix изменился
mix = np.random.permutation(even)
#np.random.shuffle(mix)
# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even, replace=False, size=3)
# Получите переменную triplet, которая должна содержать перемешанные
# значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)

print(simple)
print(randoms)
print(table)
print(even)
print(mix)
print(select)
print(triplet)

0.6059782788074047
[ 1.44214488e+03  1.51654277e+02  5.28813265e+02  2.01501516e+03
  1.28240517e+02  2.38594033e+02  1.48460111e+03  1.28755048e+03
  1.55273730e+03  6.03577336e+01 -2.28417401e+01  1.93936169e+03
  1.18854621e+03  3.80736459e+01  1.06852230e+03  1.18847514e+03
  1.94250320e+03  1.09681462e+03  6.55790201e+02  8.31607324e+02
  2.88216888e+02  1.08596141e+03  2.73553360e+02  1.11722142e+03
  8.84076551e+02  9.74175063e+02  1.63694713e+03  1.43966053e+03
 -7.88273550e-02  1.30919192e+03  1.24700551e+03  1.64761920e+03
  2.93903055e+02  1.19056852e+03  1.19102890e+03  5.03619976e+02
  1.74254881e+03  1.13013901e+03  1.98142287e+03  8.10086179e+02
  1.24235695e+02  9.54671885e+02  7.87407805e+02  1.83850479e+03
  1.38927296e+03  1.78361285e+03  1.12847065e+03  1.23255777e+03
  5.92935602e+02  1.63845066e+03  5.12482326e+02  5.17676863e+02
  2.87071500e+02  4.25673103e+02  1.26315547e+03  1.85668749e+02
  6.93866612e+02  1.25597031e+03  1.69165738e+03 -1.14109610e+01
  7.49

Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

Для этого напишите функцию shuffle_seed(array), которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

In [108]:
def shuffle_seed(array):
    seed = np.random.randint(2 ** 32)
    np.random.seed(seed)
    result = np.random.permutation(array)
    return result, seed

    

Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.

In [109]:
import numpy as np

def get_loto(num):
    loto = np.random.randint(1, 101, size=(num, 5, 5))
    return loto

Напишите функцию get_unique_loto(num). Она так же, как и функция в задании выше, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

Функция также должна возвращать массив формы num x 5 x 5.

In [ ]:
import numpy as np

def get_unique_loto(num):
    sample = np.arange(1, 101)
    res = list()
    for i in range(num):
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    res = np.array(res)
    return res