In [2]:
# создать массив из списка
import numpy as np
arr = np.array([1,5,2,9,10])

In [2]:
arr

array([ 1,  5,  2,  9, 10])

In [5]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int8)
nd_arr.dtype # если на задавать, то по умолчанию int32

dtype('int8')

In [13]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [14]:
arr[2] = 2000
arr # не хвотило памяти

C:\Users\User\AppData\Local\Temp\ipykernel_10464\4005198755.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr[2] = 2000


array([  1,   5, -48,   9,  10], dtype=int8)

In [15]:
arr[2] = 125.5
arr # отрезает запятую, т.к. int8


array([  1,   5, 125,   9,  10], dtype=int8)

In [18]:
arr = np.float64(arr)
arr

array([  1.,   5., 125.,   9.,  10.])

In [20]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr

array([12321, -1234,  3435,  -214,   100])

In [21]:
arr = np.uint8(arr)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

In [22]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [29]:
print(arr.ndim) # размерность
print(nd_arr.ndim)
print(arr.size) # размер
print(nd_arr.size)
print(arr.shape) # форма и структура массиа
print(nd_arr.shape) # 3 строки на 3 столбца
print(arr.itemsize) # сколько весит в байтах
print(nd_arr.itemsize)

1
2
5
9
(5,)
(3, 3)
1
2


In [30]:
# создание массива из нулей, одномерный из 5 элементов
zeros_1d = np.zeros(5)
zeros_1d


array([0., 0., 0., 0., 0.])

In [31]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
zeros_3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [32]:
print(zeros_3d.shape)

(5, 4, 3)


In [37]:
# Создание range только через arange с помощью numpy позволяет
# использовать данные float 
print(np.arange(5))
print(np.arange(2.5, 5)) # шаг по умолчанию 1
print(np.arange(2.5, 5, 0.5))
print(np.arange(2.5, 5, 0.5, dtype=np.float16))



[0 1 2 3 4]
[2.5 3.5 4.5]
[2.5 3.  3.5 4.  4.5]
[2.5 3.  3.5 4.  4.5]


In [ ]:
# для работы с дробными параметрами start, stop и step лучше использовать
# функцию linspace, сигнатура:
# np.linspace(start(обязательно!), stop(обязательно!),
# num=50 (число эл. в массиве, по умолчанию 50),
# endpoint=True (включен или исключен конец диапазона), 
# retstep=False (возвращать ли использованный шаг между значениями),
# dtype=None (тип данных))


In [38]:
arr = np.linspace(1,2,10) # массив из 10 чисел между 1 и 2
arr 

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [39]:
arr = np.linspace(1,2,10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [43]:
arr, step = np.linspace(1,2,10, endpoint=True,retstep=True)
print(step)

arr, step = np.linspace(1,2,10, endpoint=False, retstep=True)
print(step)

0.1111111111111111
0.1


In [47]:
arr, step = np.linspace(-6, 21, 60, retstep=True)
print(step)

0.4576271186440678


In [48]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
step

0.45

#### Действия с массивами

In [50]:
import numpy as np
arr = np.arange(8)
print(arr)
# изменим форму массива
arr.shape = (2,4) # количество строк, количество столбцов
print(arr)


[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [55]:
arr = np.arange(8)
arr_new = arr.reshape(2,4) # метод, который не перезаписывает исходный массив
print(arr_new)
arr_new = arr.reshape((2,4), order='F') # order С - заполнение по строкам
                                    # по умолчанию, F - заполнение по столбцам
print(arr_new)
arr_trans = arr_new.transpose() # транспонирование 
print(arr_trans)

[[0 1 2 3]
 [4 5 6 7]]
[[0 2 4 6]
 [1 3 5 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


#### Индексы и срезы

In [59]:
arr = np.linspace(1,2,6) # от 1 до 2, 6 элементов
print(arr)
print(arr[2])
print(arr[2:4])
print(arr[::-1]) # печать в обратном порядке

[1.  1.2 1.4 1.6 1.8 2. ]
1.4
[1.4 1.6]
[2.  1.8 1.6 1.4 1.2 1. ]


In [68]:
nd_array = np.linspace(0,6,12, endpoint=False).reshape(3,4)
print(nd_array)
print(nd_array[1][2])
print(nd_array[1, 2]) # типа координаты срока и столбец
print(nd_array[:2, 2]) # все элементы из колонки 3 (считаем от 0)
                            # для первых 2х строк
print(nd_array[1:, 2:4]) # строка от 1 (нулевая не вошла), столбцы от 2 до 4
print(nd_array[:, 2:4])
print(nd_array[:2]) # все столбцы 2 строки первые ( 0 и 1 )


[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
3.0
3.0
[1. 3.]
[[3.  3.5]
 [5.  5.5]]
[[1.  1.5]
 [3.  3.5]
 [5.  5.5]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]]


In [80]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)
elem_5_3 = mystery[4, 2]
last = mystery[-1, -1]
line_4 = mystery[3]
col_2 = mystery[:,-2]
part = mystery[1:4, 2:5]
rev = mystery[::-1,-1]
trans = mystery.transpose()

print(elem_5_3)
print(last)
print(line_4)
print(col_2)
print(part)
print(rev)
print(trans)

11740
-32037
[13240  7994 32592 20149 13754 11795  -564]
[-17182  15790  25397  11795  12578    -47]
[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]
[-32037  29943   -564   8225   7181 -18049]
[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


#### Сортировка одномерных массивов

In [82]:
# 1й способ
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
print(arr_new)

# 2й способ
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
print(arr)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]
None
[ 3  4 12 12 15 23 23 45]


#### Работа с пропущенными данными

In [94]:
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data) # квадратный корень от чисел массива
print(roots) # вышло предупреждение о некорректном элементе NAN



[2.         3.                nan 1.73205081]


C:\Users\User\AppData\Local\Temp\ipykernel_10464\1563749654.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data) # квадратный корень от чисел массива


In [85]:
print(None == None)
print(np.nan == np.nan)
print(None is None)
print(np.nan is np.nan)
print(np.nan is None)

True
False
True
True
False


In [91]:
sum(roots)

nan

In [95]:
# находим nan в массиве
print(np.isnan(roots))
roots[np.isnan(roots)] = 0 # заменили nan на 0
print(roots)
print(sum(roots))

[False False  True False]
[2.         3.         0.         1.73205081]
6.732050807568877


In [98]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
nans_index = np.isnan(mystery)
n_nan = sum(nans_index)
mystery_new = mystery[np.isnan(mystery)] = 0
mystery_int = np.int32(mystery)
array = np.sort(mystery)
table = mystery.reshape((5,2), order='F')
col = table[:,1]

In [6]:
def get_chess(a):
    arr = np.zeros((a, a))
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr

get_chess(4)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.